/* 공동육아 놀이 목록 — 놀이를 추가·수정할 때는 이 파일만 고치면 돼요.
   src: daycare=어린이집 계획안 응용(🏫), kr=국내 공공자료(원문 미확인), intl=해외 자료(원문 미확인), past=지난 회차, life=직접 제안
   used: 해 본 회차 날짜. 공지를 낸 뒤 여기에 적어 주세요. */
const PLAYS = [
  {id:'box-mystery', name:'궁금이 상자', cat:'넣고 빼기', how:'빈 티슈 상자 속 손수건·양말을 쏙쏙 뽑아요.', items:['빈 티슈 상자','손수건','양말'], src:'daycare', orig:'궁금이 상자 안에 뭐가 있을까?', used:'10/05'},
  {id:'diaper-peek', name:'기저귀 까꿍', cat:'까꿍·찾기', how:'새 기저귀로 얼굴을 가렸다가 까꿍!', items:['새 기저귀'], src:'daycare', orig:'기저귀로 까꿍놀이', used:'10/05'},
  {id:'box-tunnel', name:'상자 터널', cat:'몸으로', how:'양쪽 뚫은 택배 상자를 기어서 통과. 반대편에서 "안녕!" "빠이!"', items:['택배 상자'], src:'daycare', orig:'커다란 터널을 통과해요', used:'10/05'},
  {id:'tissue-tower', name:'휴지 쌓고 와르르', cat:'넣고 빼기', how:'두루마리 휴지를 블록처럼 쌓고 무너뜨려요.', items:['두루마리 휴지'], src:'daycare', orig:'소프트 블록 쌓고 무너뜨려요', used:'10/05'},
  {id:'box-car', name:'상자 자동차', cat:'몸으로', how:'끈 묶은 상자에 인형을 태워 끌고 다녀요.', items:['택배 상자','끈','인형'], src:'daycare', orig:'줄달린 자동차를 끌어요', used:'10/05', song:'간다 간다'},
  {id:'bag-tidy', name:'장바구니에 담아 정리', cat:'마무리', how:'놀잇감을 바구니에 담으며 "도와줘서 고마워".', items:['장바구니','빨래 바구니'], src:'daycare', orig:'내 가방에 좋아하는 놀잇감을 담아요', used:'10/05', song:'모두 제자리'},
  {id:'pot-drum', name:'냄비 드럼', cat:'소리·노래', how:'냄비·분유통을 실리콘 숟가락으로 두드려요.', items:['냄비','분유통','실리콘 숟가락'], src:'daycare', orig:'분유통 드럼을 연주해요', used:'10/02', song:'산토끼'},
  {id:'freeze', name:'멈춰라, 얼음!', cat:'소리·노래', how:'노래가 멈추면 다 같이 얼음.', items:['블루투스 스피커'], src:'past', used:'10/02', song:'머리 어깨 무릎 발'},
  {id:'uke', name:'우쿨렐레 줄 튕겨 보기', cat:'소리·노래', how:'빠르게, 느리게 쳐 주고 아이도 줄을 튕겨 봐요.', items:['우쿨렐레'], src:'past', used:'10/02', song:'곰 세 마리'},
  {id:'sock-off', name:'엄마 아빠 양말 벗기기', cat:'흉내·책', how:'어른 양말을 잡아당겨 벗기고 신어 보기도 해요.', items:['어른 양말'], src:'daycare', orig:'우리 가족 양말 신고 벗어요'},
  {id:'big-shoes', name:'엄마 아빠 실내화 신고 걷기', cat:'몸으로', how:'큰 실내화에 발을 넣고 뒤뚱뒤뚱 걸어요.', items:['실내화'], src:'daycare', orig:'빅빅이 신발 신고 걸어요'},
  {id:'basket-stroller', name:'바구니 유모차 밀기', cat:'몸으로', how:'빨래 바구니에 인형을 태우고 밀고 다녀요.', items:['빨래 바구니','인형'], src:'daycare', orig:'동물 인형을 유모차에 태워요'},
  {id:'sock-puppet', name:'양말 손인형', cat:'흉내·책', how:'양말을 손에 끼우고 "안녕?" 말 걸기.', items:['양말'], src:'daycare', orig:'동물 손 인형으로 놀이해요'},
  {id:'sock-worm', name:'양말 애벌레', cat:'흉내·책', how:'양말에 양말을 채워 꼬물꼬물 기어가는 흉내.', items:['양말'], src:'daycare', orig:'양말 애벌레로 놀이해요'},
  {id:'blanket-sled', name:'이불 썰매', cat:'몸으로', how:'아이를 이불에 앉히고 천천히 끌어요.', items:['얇은 이불'], src:'daycare', orig:'튜브 썰매를 타요'},
  {id:'hanky-fly', name:'손수건 날리기', cat:'까꿍·찾기', how:'손수건을 위로 던져 팔랑팔랑 떨어지는 걸 잡아요.', items:['손수건'], src:'daycare', orig:'색깔 스카프로 놀이해요'},
  {id:'cushion-hill', name:'이불·쿠션 산 넘기', cat:'몸으로', how:'쿠션을 쌓고 이불을 덮어 오르고 내려가요.', items:['이불','쿠션'], src:'daycare', orig:'매트 위를 올라가고 내려가요'},
  {id:'sock-goal', name:'양말 공 골대', cat:'넣고 빼기', how:'양말을 말아 공을 만들어 바구니에 쏙.', items:['양말','빨래 바구니'], src:'daycare', orig:'골대에 공을 넣어요'},
  {id:'bottle-roll', name:'페트병 굴리기', cat:'몸으로', how:'뚜껑을 꽉 잠근 빈 페트병을 굴리고 쫓아가요.', items:['빈 페트병'], src:'daycare', orig:'젖병 마라카스를 굴려요'},
  {id:'tube-mic', name:'휴지심 마이크', cat:'소리·노래', how:'휴지심에 대고 "아~" 소리 내고 옹알이 주고받기.', items:['휴지심'], src:'daycare', orig:'마이크에 대고 옹알이해요'},
  {id:'hand-song', name:'동요 손유희', cat:'소리·노래', how:'스피커로 동요를 틀고 손동작 따라 하기.', items:['블루투스 스피커'], src:'daycare', orig:'동요 따라 손유희', song:'간다 간다'},

  {id:'basket-boat', name:'바구니 배 타기', cat:'몸으로', how:'빈 빨래 바구니에 앉혀 천천히 밀며 "배 타고 가요".', items:['빨래 바구니'], src:'kr', orig:'정리 바구니가 배처럼 움직이는 놀이'},
  {id:'cloth-peek', name:'천 뒤 까꿍', cat:'까꿍·찾기', how:'큰 보자기를 덮었다 걷으며 까꿍.', items:['보자기','손수건'], src:'kr', orig:'천으로 놀아요'},
  {id:'newspaper', name:'신문지 구기고 찢기', cat:'넣고 빼기', how:'바스락 소리 듣고 구기고 찢어요. 조각은 입에 넣지 않게 바로 치워요.', items:['신문지'], src:'kr', orig:'신문지 놀이'},
  {id:'tube-roll', name:'휴지심 굴리고 쌓기', cat:'넣고 빼기', how:'휴지심 여러 개를 굴리고 세워 쌓아요.', items:['휴지심'], src:'kr', orig:'휴지심 놀이'},
  {id:'cushion-stones', name:'방석 징검다리', cat:'몸으로', how:'방석을 띄엄띄엄 깔고 기어서 건너요.', items:['방석'], src:'kr', orig:'가족 물건 활용 놀이'},
  {id:'book-together', name:'그림책 함께 보기', cat:'흉내·책', how:'모여 앉아 한 권을 보며 그림 속 물건 이름 짚기.', items:['그림책'], src:'kr', orig:'북스타트 그림책 읽어 주기'},

  {id:'obstacle', name:'장애물 코스', cat:'몸으로', how:'상자 통과 → 쿠션 넘기 → 이불 더미 → 부모 품으로.', items:['택배 상자','쿠션','이불'], src:'intl', orig:'Toddler obstacle course'},
  {id:'popcorn', name:'팝콘 놀이', cat:'몸으로', how:'이불 위 양말 공을 여럿이 흔들어 "팝콘!" 떨어지면 다시 올려요.', items:['이불','양말'], src:'intl', orig:'Popcorn Game'},
  {id:'scarf-tube', name:'심에서 손수건 빼기', cat:'넣고 빼기', how:'키친타월 심에 손수건을 끼워 두면 아이가 잡아당겨 빼요.', items:['키친타월 심','손수건'], src:'intl', orig:'Scarf through a tube'},
  {id:'fill-dump', name:'담고 쏟기', cat:'넣고 빼기', how:'신문지 공을 바구니에 담았다가 상자에 와르르 쏟아요.', items:['신문지','바구니','택배 상자'], src:'intl', orig:'Fill and Dump'},
  {id:'loud-quiet', name:'시끄러운 통·조용한 통', cat:'소리·노래', how:'플라스틱 컵 통과 행주 통을 흔들어 소리 비교.', items:['통 2개','플라스틱 컵','행주'], src:'intl', orig:'Loud vs quiet buckets'},
  {id:'box-blocks', name:'상자 블록 쌓기', cat:'넣고 빼기', how:'크기 다른 상자를 큰 블록처럼 쌓고 무너뜨려요.', items:['택배 상자'], src:'intl', orig:'Build with boxes'},
  {id:'cozy-box', name:'상자 속 아늑한 책방', cat:'흉내·책', how:'큰 상자 안에 담요·인형을 넣고 같이 그림책 보기.', items:['택배 상자','담요','인형','그림책'], src:'intl', orig:'Cozy corner'},
  {id:'dress-up', name:'소품 흉내 놀이', cat:'흉내·책', how:'스카프 두르고 가방 메고 엄마 아빠 흉내.', items:['스카프','가방'], src:'intl', orig:'Dress-up props'},
  {id:'hide-seek', name:'수건 밑 인형 찾기', cat:'까꿍·찾기', how:'수건 밑에 인형을 숨기고 "어디 갔지?" 찾아요.', items:['수건','인형'], src:'intl', orig:'Hide and Search'},
  {id:'spoon-move', name:'숟가락질', say:'숟가락 해 볼래?', cat:'우리 일 함께하기', how:'큰 숟가락·국자로 양말 공을 이 그릇에서 저 그릇으로 옮겨요.', items:['큰 숟가락','국자','그릇 2개','양말'], src:'life'},
  {id:'diaper-bin', name:'쓰레기통에 버리기', say:'이거 버려 줄래?', cat:'우리 일 함께하기', how:'새 기저귀를 돌돌 말아 뚜껑 있는 통에 쏙. "버려 줘서 고마워!"', items:['새 기저귀','뚜껑 있는 빈 통'], src:'life'},
  {id:'put-in', name:'바구니에 넣기', say:'이거 넣어 줄래?', cat:'우리 일 함께하기', how:'양말·손수건을 하나씩 건네며 바구니에 넣어 달라고 부탁해요.', items:['양말','손수건','빨래 바구니'], src:'life'},
  {id:'laundry', name:'빨래 개기', say:'빨래 이거 개 줄래?', cat:'우리 일 함께하기', how:'마른 수건·손수건을 반으로 접는 시늉, 짝 양말 찾기, 바구니에 담기.', items:['수건','손수건','양말','빨래 바구니'], src:'life'},
  {id:'cup-drink', name:'컵으로 물 마시기', say:'빨대 없이 마셔 볼래?', cat:'우리 일 함께하기', how:'작은 컵에 물을 한 모금만 따라 두 손으로 잡고 마셔요. 수건을 무릎에 깔아요.', items:['작은 컵','물병','수건'], src:'life', water:true},
  {id:'wipe', name:'쓱싹쓱싹 닦기', say:'쓱싹쓱싹 닦아 볼래?', cat:'우리 일 함께하기', how:'젖은 손수건으로 탁자·바닥·인형 얼굴을 쓱싹쓱싹.', items:['손수건','분무기','인형'], src:'life', water:true},
  {id:'veggie-wash', name:'야채 씻기', say:'야채 씻어 볼래?', cat:'우리 일 함께하기', how:'대야에 물을 조금 받아 통감자·당근을 문질러 씻어요. 먹지 않고 씻기만, 다 쓰면 집에 가져가요.', items:['대야','통감자·당근','수건'], src:'life', water:true},
  {id:'hand-wash', name:'손 씻기', say:'손 씻어 볼래?', cat:'우리 일 함께하기', how:'대야 물에 손을 담그고 비비비, 수건으로 톡톡 닦아요.', items:['대야','수건'], src:'life', water:true, song:'손을 씻어요'},
  {id:'shoe-shelf', name:'신발 정리', say:'신발 넣어 줄래?', cat:'우리 일 함께하기', how:'실내화를 벗어서 상자 신발장에 넣어요.', items:['실내화','택배 상자'], src:'life'},
  {id:'sleeve', name:'옷 입기', say:'팔 쏙 넣어 볼래?', cat:'우리 일 함께하기', how:'엄마 아빠의 헐렁한 티셔츠 소매에 팔을 쏙.', items:['헐렁한 티셔츠'], src:'life'},
  {id:'doll-sleep', name:'인형 재우기', say:'아기 재워 줄래?', cat:'우리 일 함께하기', how:'인형에게 손수건 이불을 덮고 토닥토닥.', items:['인형','손수건'], src:'life', song:'자장가'},
  {id:'ice-touch', name:'얼음 만져 보기', cat:'감각', how:'대야에 큰 얼음덩어리를 넣고 만지고 밀어 봐요. "차가워!" 작은 조각은 치워요.', items:['대야','큰 얼음(컵에 얼린 것)','수건'], src:'life', water:true},
  {id:'ice-bag', name:'얼음 지퍼백 주무르기', cat:'감각', how:'얼음과 물을 지퍼백에 넣고 꽉 잠가 손바닥으로 눌러 봐요.', items:['지퍼백','얼음','수건'], src:'life'},
  {id:'textures', name:'여러 촉감 만져 보기', cat:'감각', how:'수건, 비닐봉지, 냄비 뚜껑, 털 인형을 차례로 만지며 "보들보들, 바스락, 차가워".', items:['수건','비닐봉지','냄비 뚜껑','인형'], src:'life'},
  {id:'cup-stack', name:'컵·통 쌓기', cat:'넣고 빼기', how:'플라스틱 컵, 빈 반찬통을 쌓고 겹쳐 넣어요.', items:['플라스틱 컵','빈 반찬통'], src:'intl', orig:'Stacking cups'},
];
const CATS = ['전체','몸으로','까꿍·찾기','넣고 빼기','소리·노래','감각','흉내·책','우리 일 함께하기','마무리'];
const CAT_DESC = {
  '몸으로':'기고, 오르고, 밀고, 끌며 온몸을 쓰는 놀이',
  '까꿍·찾기':'가렸다 나타나고, 숨긴 걸 찾는 놀이',
  '넣고 빼기':'담고, 뽑고, 쌓고, 무너뜨리는 놀이',
  '소리·노래':'두드리고 흔들고 따라 부르는 놀이',
  '흉내·책':'엄마 아빠 흉내, 인형, 그림책',
  '우리 일 함께하기':'엄마 아빠가 하는 일을 "~해 볼래?" 하고 맡겨 보는 상황극. 같은 걸 몇 주 반복해요',
  '감각':'차갑고, 보들보들하고, 바스락거리는 걸 만져 보는 놀이',
  '마무리':'놀잇감을 함께 담으며 끝내기'};
const SRC_TAG = {daycare:'🏫 어린이집', kr:'국내 자료 · 원문 미확인', intl:'해외 자료 · 원문 미확인', past:'지난 회차', life:'직접 제안'};
